### ISSUE TITLE
Error when running Flutter web with `--web-experimental-hot-reload` after upgrading to Flutter 3.32.0 (Hive: `TypeError: dart.nullCheck(...)[$open] is not a function`)

### ISSUE THREAD

**Issue by AliKarimiENT** [IO-Design-Team/hive_ce#142]
### Steps to reproduce

- **Flutter version:** 3.32.0 (channel stable, revision be698c48a6, Dart 3.8.0)
- **Engine revision:** 1881800949
- **DevTools:** 2.45.1
- **OS:** macOS
- **Hive version:** _(please insert exact version here)

1. Upgrade Flutter to version 3.32.0.
2. Ensure `launch.json` contains:
    ```json
    {
      "name": "frontend-app",
      "request": "launch",
      "type": "dart",
      "args": ["--web-experimental-hot-reload"],
      "program": "lib/main.dart"
    }
    ```
3. Run the app with:
    ```
    flutter run -d chrome --web-experimental-hot-reload
    ```
4. Observe the error below.

### Expected results

- The app should run with `--web-experimental-hot-reload` enabled, without error.

### Actual results

Error when running Flutter web with `--web-experimental-hot-reload` after upgrading to Flutter 3.32.0 (Hive: `TypeError: dart.nullCheck(...)[$open] is not a function`)

- The same code works without `--web-experimental-hot-reload`.
- This issue started after upgrading Flutter to 3.32.0.
- Please specify if this is a known incompatibility with Hive and the new Flutter version or if there are any recommended workarounds.

### `main.dart`
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setPathUrlStrategy();
  await initializeDependencies();
  await initFirebase();

  await Hive.initFlutter();

  runApp(
    // ...
  );
}
```

### `launch.json`
```json
{
  "name": "frontend-app",
  "request": "launch",
  "type": "dart",
  "args": ["--web-experimental-hot-reload"],
  "program": "lib/main.dart"
}
```

### Logs

<details open><summary>Logs</summary>

```console
[alikarimi@Alis-MacBook-Pro frontend-app % flutter run -d chrome --web-experimental-hot-reload
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             13.4s
This app is linked to the debug service: ws://127.0.0.1:63589/caPMdTxuWNw=/ws
Debug service listening on ws://127.0.0.1:63589/caPMdTxuWNw=/ws

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on Chrome is available at: http://127.0.0.1:63589/caPMdTxuWNw=
Starting application from main method in: org-dartlang-app:/web_entrypoint.dart.
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:63589/caPMdTxuWNw=
TypeError: dart.nullCheck(...)[$open] is not a function
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3328:77           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3366:20           open
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6608:55           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6672:20           [_openBox]
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6694:54           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6706:20           openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93260:50   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93278:20   openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93312:45   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93325:20   readItem
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93442:36   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93451:20   getAccessToken
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74442:185  <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74458:20   readTokens
package:langujet/main.dart.lib.js 232:185                                         <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44259:42                                                        <fn>
dart:sdk_internal 43193:59                                                        runUnary
dart:sdk_internal 35859:26                                                        handleValue
dart:sdk_internal 36558:47                                                        handleValueCallback
dart:sdk_internal 36596:15                                                        _propagateToListeners
dart:sdk_internal 36415:21                                                        [_completeWithValue]
dart:sdk_internal 36461:33                                                        callback
dart:sdk_internal 44642:13                                                        _microtaskLoop
dart:sdk_internal 44649:13                                                        _startMicrotaskLoop
dart:sdk_internal 3792:46                                                         tear
dart:sdk_internal 36899:9                                                         <fn>
TypeError: dart.nullCheck(...)[$open] is not a function
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3328:77           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 3366:20           open
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6608:55           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6672:20           [_openBox]
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6694:54           <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:hive/src/box_collection/box_collection_stub.dart.lib.js 6706:20           openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93260:50   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93278:20   openBox
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93312:45   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93325:20   readItem
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93442:36   <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 93451:20   getAccessToken
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74442:185  <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44240:5                                                         _asyncStartSync
package:langujet/features/home/presentation/widgets/banner.dart.lib.js 74458:20   readTokens
package:langujet/main.dart.lib.js 232:185                                         <fn>
dart:sdk_internal 44282:13                                                        <fn>
dart:sdk_internal 44292:7                                                         <fn>
dart:sdk_internal 44259:42                                                        <fn>
dart:sdk_internal 43193:59                                                        runUnary
dart:sdk_internal 35859:26                                                        handleValue
dart:sdk_internal 36558:47                                                        handleValueCallback
dart:sdk_internal 36596:15                                                        _propagateToListeners
dart:sdk_internal 36415:21                                                        [_completeWithValue]
dart:sdk_internal 36461:33                                                        callback
dart:sdk_internal 44642:13                                                        _microtaskLoop
dart:sdk_internal 44649:13                                                        _startMicrotaskLoop
dart:sdk_internal 3792:46              
]
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Paste your output here]
```

</details>

**Comment by Rexios80** [comment]
Wouldn't this be an issue with web hot reload and not Hive? I'm pretty sure package developers aren't supposed to have to do anything to support this.

**Comment by AliKarimiENT** [comment]
> Wouldn't this be an issue with web hot reload and not Hive? I'm pretty sure package developers aren't supposed to have to do anything to support this.

Thanks for your response I will actually also report on this issue on the flutter repo and they told me that this issue is related to the package. The point is that when I remove the line I added to the config for the hot reload feature, it works.

**Comment by Rexios80** [comment]
For reference: https://github.com/flutter/flutter/issues/169222

**Comment by Rexios80** [comment]
For reference: https://github.com/flutter/flutter/issues/169222

**Comment by Rexios80** [comment]
Wait this is from the original Hive package? Why did you report this here?
